"""bjj_techniques_expansion

Revision ID: 26fcf71a7ef4
Revises: 20260319_0002
Create Date: 2026-03-19 21:56:15.109665
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '26fcf71a7ef4'
down_revision = '20260319_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bjj_techniques',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('gi_mode', sa.String(length=16), nullable=False),
    sa.Column('created_by_user', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bjj_techniques_created_by_user'), 'bjj_techniques', ['created_by_user'], unique=False)
    op.create_index(op.f('ix_bjj_techniques_name'), 'bjj_techniques', ['name'], unique=False)
    op.create_table('bjj_session_techniques',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('technique_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['bjj_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['bjj_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'technique_id', 'type')
    )
    op.add_column('bjj_sessions', sa.Column('round_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bjj_sessions', 'round_duration_minutes')
    op.drop_table('bjj_session_techniques')
    op.drop_index(op.f('ix_bjj_techniques_name'), table_name='bjj_techniques')
    op.drop_index(op.f('ix_bjj_techniques_created_by_user'), table_name='bjj_techniques')
    op.drop_table('bjj_techniques')
    # ### end Alembic commands ###
